# This is a basic workflow to help you get started with Actions

name: Deployment With Repo Dependency
on:
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: Delight-Fela-Steve/build_script.git
          ref: main
          fetch-depth: 1

      # Runs a set of commands using the runners shell
      - name: Copy the build file
        run: |
          cp build.sh ../build.sh
          ls

      - name: Deploy the build
        run: |
          ls
  # deploy:
  #   needs: build
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v3

  #     - name: Deploy the build
  #       run: |
  #         ls
  #         # cp ../build.sh
  #         # bash ../build.sh
